### ISSUE TITLE
hello i have been trying to use this event api but its not working anymore is there any solution?

### ISSUE THREAD

**Issue by brwa88** [PedroGabriel/facebook-events-by-location#1]

**Comment by PedroGabriel** [comment]
Just saw in the original node.js version this message:

> This package is currently no longer usable, because FB changed the way one can access the event data. It seems that access to the Events API is no longer granted, see the lengthy discussion at [facebook-events-by-location-core/#29](https://github.com/tobilg/facebook-events-by-location-core/issues/29).

So probably there is no workaround and im going to archive the whole repo, sorry about that.
